from FallenRobot import DEMONS, DEV_USERS, DRAGONS, TIGERS, WOLVES, telethn

IMMUNE_USERS = DRAGONS + WOLVES + DEMONS + TIGERS + DEV_USERS

IMMUNE_USERS = (
    list(DRAGONS) + list(WOLVES) + list(DEMONS) + list(TIGERS) + list(DEV_USERS)
)
